FROM dockerfile/nodejs


# Set the working directory
WORKDIR   /src

EXPOSE  3000

CMD ["/bin/bash"]


# docker build -t test1 .
# docker run -it --rm -p 8080:3000 -v `pwd`:/src test1

# npm install
# node app.js
# http://localhost:8080

# docker run -it -p 8080:3000 -v /home/sizhexi/docker/test1:/src test14
# docker run -it -p 8080:3000 -v /home/sizhexi/docker/test1:/src test1 
