FROM google/nodejs


# Set the working directory
WORKDIR   /src

EXPOSE  3000

CMD ["/bin/bash"]


# docker build -t test2 .
# docker run -it --rm -p 8080:3000 -v `pwd`:/src test2

# npm install
# node app.js
# http://localhost:8080